export AJ_TASK_INDEX="${VK_TASK_INDEX:-0}"
JOB_NAME="${HOSTNAME%-${AJ_TASK_NAME}-${AJ_TASK_INDEX}}"
export AJ_NODE_RANK=$(({RANK_BASE} + AJ_TASK_INDEX))
export NODE_RANK="${NODE_RANK:-$AJ_NODE_RANK}"
export RANK="${RANK:-$NODE_RANK}"
export WORLD_SIZE="${WORLD_SIZE:-$AJ_NODES}"
export MASTER_ADDR="${MASTER_ADDR:-${JOB_NAME}-master-0.${JOB_NAME}}"
export MASTER_PORT="${MASTER_PORT:-6105}"
