"""Azure ML / ARM REST client package — pure HTTP, no azure-ai-ml SDK."""

from .arm import (
    AzureARMClient,
    ComputeInfo,
    ComputesAPI,
    IdentitiesAPI,
    InstanceTypeInfo,
    InstanceTypesAPI,
    ManagedIdentityInfo,
    ResourceGraphAPI,
    SLA_TIERS,
    SeriesQuota,
    SlaTierQuota,
    StorageAccountInfo,
    StoragesAPI,
    SubscriptionsAPI,
    VCInfo,
    VCQuotaAPI,
    VirtualClustersAPI,
    WorkspaceInfo,
    WorkspacesAPI,
    parse_managed_quotas,
)
from .auth import WorkspaceCoords
from .ml import (
    AzureMLClient,
    BlobAPI,
    DEFAULT_POLL_INTERVAL,
    DatastoreInfo,
    DatastoresAPI,
    EnvironmentInfo,
    EnvironmentsAPI,
    JobInfo,
    JobsAPI,
    LogStreamer,
    LogsAPI,
    RestContext,
    create_rest_client,
)

__all__ = [
    "AzureARMClient",
    "ComputeInfo",
    "ComputesAPI",
    "IdentitiesAPI",
    "InstanceTypeInfo",
    "InstanceTypesAPI",
    "ManagedIdentityInfo",
    "ResourceGraphAPI",
    "SLA_TIERS",
    "SeriesQuota",
    "SlaTierQuota",
    "StorageAccountInfo",
    "StoragesAPI",
    "SubscriptionsAPI",
    "VCInfo",
    "VCQuotaAPI",
    "VirtualClustersAPI",
    "WorkspaceInfo",
    "WorkspacesAPI",
    "parse_managed_quotas",
    "AzureMLClient",
    "BlobAPI",
    "DEFAULT_POLL_INTERVAL",
    "DatastoreInfo",
    "DatastoresAPI",
    "EnvironmentInfo",
    "EnvironmentsAPI",
    "JobInfo",
    "JobsAPI",
    "LogStreamer",
    "LogsAPI",
    "RestContext",
    "create_rest_client",
    "WorkspaceCoords",
]
